adding notification contextualisation support
CriminalInjuriesCompensationAuthority/data-capture-service pull request #271
Opened 2022-03-03 10:01 UTC by neil-stephen-mcgonigle

Builds upon the work Adrian completed previously and the notification client update work.

Proposed version bump 5.0.0 but open to suggestions, think with the changes to the tasks, array to map, this is a breaking change?

2022-03-03 11:00 UTC, BarryPiccinni requested changes

2022-03-03 13:10 UTC, neil-stephen-mcgonigle commented on package.json
>          "swagger-ui-express": "^4.3.0",
Leaving this until after it has been tested in UAT?

2022-03-03 14:28 UTC, BarryPiccinni approved these changes

2022-03-10 08:48 UTC, neil-stephen-mcgonigle commented on package.json
>          "swagger-ui-express": "^4.3.0",
Merged q-templates-application#notifications into q-templates-application#l10n-rc and this file is now pointing to latest q-templates-application#l10n-rc

2022-03-10 08:53 UTC, neil-stephen-mcgonigle commented on questionnaire/questionnaire-service.js
>      }
As discussed created a new ticket [CICA-116](https://dsdmoj.atlassian.net/browse/CICA-116) to address this in more depth. 
Ideally we should allow any unhandled exceptions to propagate up and be handled by the calling method or framework.
Or alternatively modify the q-template-validator and q-schema to ensure the template conforms to the correct shape.

2022-03-10 08:54 UTC, merged