Bp refactor/remove v1 api
CriminalInjuriesCompensationAuthority/data-capture-service pull request #421
Opened 2023-11-29 10:18 UTC by BarryPiccinni

Remove v1 API contract.

 - Remove v1 Schema
 - Remove config for v1, eg build step
 - Update/remove tests which have been broken or made redundant by the above.

2023-12-01 11:28 UTC, armoj requested changes

2023-12-01 11:28 UTC, armoj commented on questionnaire/dataset/dataset-routes.test.js
should the dataset endpoint be getting deprecated soon enough? It, and these respective tests, are redundant now are they not?

2023-12-01 11:28 UTC, armoj commented on openapi/src/json-schemas/api/_questionnaires/post/req/201.json
this is correcting a previous mistake, yeah?

2023-12-01 11:36 UTC, BarryPiccinni commented on openapi/src/json-schemas/api/_questionnaires/post/req/201.json
It actually said "V2 dereferenced contract saved" and I assumed it was capitalised when I removed the "V2". I'll change it to lower case.

2023-12-01 11:37 UTC, BarryPiccinni commented on questionnaire/dataset/dataset-routes.test.js
Yep, but there's a separate ticket in the backlog to removed all the code.

2023-12-01 11:39 UTC, armoj commented on questionnaire/dataset/dataset-routes.test.js
yeah cool. Wasn't meaning that it should be removed alongside this stuff. Just making sure I fully understand things from my perspective 🤝

2023-12-01 11:40 UTC, armoj commented on openapi/src/json-schemas/api/_questionnaires/post/req/201.json
I was referring to this file having the required and properties updated. Looks like it was accidently left out when developing S&R

2023-12-01 11:48 UTC, BarryPiccinni commented on openapi/src/json-schemas/api/_questionnaires/post/req/201.json
Sorry, was looking at the wrong file! So this wasn't a mistake, when S+R was added this file was created with the correct `required` and `owner` properties. Github is flagging this as a change because the file is now named the same thing as the v1 file which had neither the `required` nor the `owner` property.

2023-12-04 11:27 UTC, armoj requested changes

2023-12-04 11:27 UTC, armoj commented on questionnaire/dataset/dataset-routes.test.js
> +const filepath = 'openapi/src/json-schemas/api/v2_questionnaires_{questionnaireId}_dataset/get/res';
Is this correct? I can see that this v2_questionnaires directory has been deleted

2023-12-04 12:08 UTC, armoj approved these changes

2023-12-04 12:46 UTC, merged