Feature/central error logging
CriminalInjuriesCompensationAuthority/data-capture-service pull request #430
Opened 2023-12-21 11:35 UTC by neil-stephen-mcgonigle

WIP

2023-12-22 10:52 UTC, neil-stephen-mcgonigle commented
I will add another test for the [error-handler](https://github.com/CriminalInjuriesCompensationAuthority/data-capture-service/blob/57f1731c9ad4206ba6858b6e7dc0d18ebf09c994/middleware/error-handler/index.js#L16)

2023-12-22 12:48 UTC, armoj requested changes

2023-12-22 12:48 UTC, armoj commented on questionnaire/submissions/submissions-service.test.js
> +            // submittable but unsuccessful due to failing task, default retires
do you mean "default retries" here?

2023-12-22 14:29 UTC, neil-stephen-mcgonigle commented on questionnaire/submissions/submissions-service.test.js
> +            // submittable but unsuccessful due to failing task, default retires
yup

2024-01-11 10:32 UTC, armoj approved these changes

2024-01-15 12:48 UTC, merged